site_name: Agentic AI Documentation

site_description: Comprehensive documentation for Agentic AI platform

site_url: https://ibrahim-shaban-qabaqebo.github.io/Agentic-AI-Docs

repo_name: Agentic-AI-Docs

repo_url: https://github.com/ibrahim-shaban-qabaqebo/Agentic-AI-Docs

edit_uri: edit/master/docs/

copyright: Copyright &copy; 2024 Agentic AI

nav:
  - index.md

extra:
  # hide the "Made with Material for MkDocs" message
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibrahim-shaban-qabaqebo

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme)"
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-auto
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: "Switch to system preference"
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - toc.follow
  icon:
    repo: fontawesome/brands/github

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

extra_css:
  - "assets/stylesheets/extra.css"

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true