[project]
name = "agentic-ai-docs"
version = "0.1.0"
description = "Documentation for Agentic AI platform"
requires-python = ">=3.10"
dependencies = [
    "mkdocs-material>=9.5.0",
    "mkdocs-minify-plugin>=0.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
